### ISSUE TITLE
Unable to render Angular 4 app inside web view (help required)

### ISSUE THREAD

**Issue by kzxperience** [skpm/with-webview#11]
Hi,

first of all... much appreciation for your module!

Unfortunately, I having issues trying to render a web view created using Angular 4. I new to developing plugins for Sketch and I would like to display an SPA inside the web view. 

Could you be so kind, to assist me on this topic?

Best regards

**Comment by mathieudutour** [comment]
please be more specific

**Comment by kzxperience** [comment]
I have created an angular app for the UI inside the Sketch plugin, which has been built using the Angular CLI and pointed the regarding html file inside the my-command.js file, when creating the new WebUI object.

The web view displays the "app loading" text from the angular app however, it doesn´t redirect to the appropriate initial view of my app. 

I hope you can follow...


Thank you for your quick response

**Comment by nichenqin** [comment]
@kzxperience If you init project by `Angular cli`, maybe you forget to config `webpack.skpm.config.js`, the webpack configs created by cli will not effect the skpm webpack config, you should copy or specify all configs which angular need.(for example the `typescript` loader)

**Comment by kzxperience** [comment]
@nichenqin Thank you for your assistance. Where can I find the webpack.skpm.config.js?

**Comment by nichenqin** [comment]
Did you init plugin project by `skpm`? The file is in root folder. The file stucture is inside the `template` folder of this project(@skpm/with-webview)

**Comment by kzxperience** [comment]
No, I used the npm command proposed [here](https://github.com/skpm/sketch-module-web-view).

**Comment by nichenqin** [comment]
Maybe you should init it by `skpm`, you need a bundler to convert your code to run in sketch, which mentioned [here](https://github.com/skpm/sketch-module-web-view/blob/master/README.md#installation)

**Comment by kzxperience** [comment]
I will give it a try! 

Thanks for the hint and your support.
