### ISSUE TITLE
Template causes sketch to crash by initial startup

### ISSUE THREAD

**Issue by lukasholzer** [skpm/with-webview#14]
# Bug

## Description
When I create a new project with `skpm create my-plugin --template=skpm/with-webview`
and I use the template from this space it will successful generate my skeleton plugin.

When I run afterwards `npm run start` Sketch and the app will crash with the following failure message.

<img width="545" alt="screenshot 2018-11-20 at 19 39 10" src="https://user-images.githubusercontent.com/11156362/48795275-9d504f80-ecfc-11e8-8b14-a6e77b692a82.png">

<img width="1306" alt="screenshot 2018-11-20 at 19 39 41" src="https://user-images.githubusercontent.com/11156362/48795125-3f236c80-ecfc-11e8-9f87-9a89640ea788.png">

## Versions

- node: v10.6.0
- npm: 6.4.1
- skpm: 1.1.9

**Comment by mathieudutour** [comment]
Ah yes, `npm start` will run the command every time there is a change so it doesn't play well with a long running script.

Using `npm run watch` and launching the webview manually should fix it. I should just remove the start script
