### ISSUE TITLE
Cash when double click to install ?

### ISSUE THREAD

**Issue by beyondyuanshu** [skpm/with-webview#17]
1. build plugin with the "Usage";
2.click the plugin to install;
3.run the plugin

![image](https://user-images.githubusercontent.com/3970169/63682952-b4901080-c82b-11e9-9631-364b6201d9a6.png)

**Comment by robintindale** [comment]
I think the `sketch-module-web-view` dependency needs updating. Will add a PR

**Comment by robintindale** [comment]
Oh actually ignore that - the dependency should be fine. What do you get if you run `npm view sketch-module-web-view version` in your directory? The error you post looks like a bug that was fixed in the latest version of `sketch-module-web-view`

**Comment by beyondyuanshu** [comment]
Thanks. It 's OK after updated the `view sketch-module-web-view`
