### ISSUE TITLE
Hot rebuild not working

### ISSUE THREAD

**Issue by gabrielenosso** [skpm/with-webview#3]
If I change the code, it rebuilds but Sketch doesn't read the new version.
I have to close and reopen it to see the modifications.

Is there any step I missed to let it work?

**Comment by mathieudutour** [comment]
it depends if you use the `shouldKeepAround` option. If you do, then you need to close sketch and reopen it. That being said, if you just change the html or the js of the webview, you can just reload it (right-click -> reload)

**Comment by gabrielenosso** [comment]
I tried the plugin with the 'shouldKeepAround' option set to "false", but Sketch crashes...
Sometimes it crashes at the startup, sometimes as soon as I click on the "Get a random number" button.

**Comment by gabrielenosso** [comment]
Also, using 'npm run watch' to start the project, if I change the .html file of the webview and reload it (right-click -> reload), it doesn't show in sketch the new version.

**Comment by mathieudutour** [comment]
Yeah you need to use `shouldKeepAround` if you want to talk to the plugin

**Comment by gabrielenosso** [comment]
So is there a way to have a quick reload of the plugin - or of the webview- using 'shouldKeepAround'?
Or closing and reopening Sketch is the only way?

**Comment by mathieudutour** [comment]
You can setup a webpack dev server and point the webview to it. It’s a bit more work

**Comment by gabrielenosso** [comment]
Do you think it would be possible to close Sketch and reopen it?
Using something like: `osascript -e 'quit app "Sketch"'` from the Terminal, which soft closes the app.

**Comment by mathieudutour** [comment]
Oh yeah that’s possible but I think it’s easier to use webpack-dev-server :)

**Comment by gabrielenosso** [comment]
but the webpack-dev-server would work only for the webview, not for the plugin.
And anyway you would need a way to reload it in Sketch.. no?

**Comment by mathieudutour** [comment]
Oh yes that’s very true, I’ll try to think about it
