### ISSUE TITLE
Possibility to open a panel instead of a window

### ISSUE THREAD

**Issue by gabrielenosso** [skpm/with-webview#5]
Is there the possibility to open a panel instead of a window?
I saw this Sketch Plugin Boilerplate doing it: https://github.com/julianburr/sketch-plugin-boilerplate

Is in skpm something like that?

**Comment by mathieudutour** [comment]
Hum that shouldn't be too hard to change but that's the wrong repo ;) 

Could you open a similar issue here: https://github.com/skpm/sketch-module-web-view/issues

**Comment by gabrielenosso** [comment]
I opened the issue on the other repository as you said:
https://github.com/skpm/sketch-module-web-view/issues/19

Unfortunately I don't know a lot about the Sketch API to manage windows and panels, but I think it's the only big thing missing in this module :)

Thanks!
