### ISSUE TITLE
Executing the package runs twice

### ISSUE THREAD

**Issue by gabrielenosso** [skpm/with-webview#6]
If I build the template and then I execute the plugin.sketchplugin packet, it seems to run twice: it installs the package but then it says that the package is just installed, so it shows a prompt to choose if you want to replace it.
It does that even if you install it for the first time.

If you choose to replace the package, it fails cause the OS deletes the file before it installs it...
very weird behaviour :)

**Comment by mathieudutour** [comment]
hum you don't have to execute the `plugin.sketchplugin`, it is automatically symlinked in the right place

**Comment by gabrielenosso** [comment]
How do I build the production version?
That's what I probably missed then 😊

**Comment by mathieudutour** [comment]
`npm run build` or `NODE_ENV=production npm run build` if you have some stuff that use NODE_ENV. It is symlinked so you don't have to do anything, the latest thing you build is the one that will run in sketch

**Comment by gabrielenosso** [comment]
So for production I just take the package created in the Sketch plugins folder... Right?
Thanks!

**Comment by mathieudutour** [comment]
no no you take the `.sketchplugin` created in your repo. I'm not sure what you mean by "for production". If it's to share it, just use the `.sketchplugin` of your repo
